### ISSUE TITLE
powerline-shell.py breaks with ValueError

### ISSUE THREAD

**Issue by Datamance** [banga/powerline-shell#246] opened 2016-08-27 05:31 UTC
Here's what I see on my stacktrace:

```
Traceback (most recent call last):
  File "/Users/ricorodriguez/powerline-shell.py", line 692, in <module>
    add_fossil_segment(powerline)
  File "/Users/ricorodriguez/powerline-shell.py", line 685, in add_fossil_segment
    _add_fossil_segment(powerline)
  File "/Users/ricorodriguez/powerline-shell.py", line 655, in _add_fossil_segment
    subprocess.Popen(['fossil'], stdout=subprocess.PIPE).communicate()[0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

Also notice that when the bash script gets run, my prompt gets deleted entirely. Pretty sure that's because the script isn't running but the documentation could be clearer as to what I should expect (also in what order to do things)

**Comment by shyovn** [comment] 2016-10-19 12:30
I am having this same issue.

**Comment by wangjoshuah** [comment] 2016-10-25 23:28
I believe this is a duplicate of this. https://github.com/banga/powerline-shell/issues/236
It's caused by a bug in python. https://bugs.python.org/issue26083
You can download the latest verison of python 2.7.12 here https://www.python.org/ftp/python/2.7.12/python-2.7.12-macosx10.6.pkg

**Comment by b-ryan** [comment] 2017-09-30 22:02
Thanks @wangjoshuah 

Just added this to the FAQ: https://github.com/banga/powerline-shell/wiki/FAQ#valueerror-insecure-string-pickle

**Closed by b-ryan** 2017-09-30 22:02 UTC
