### ISSUE TITLE
Shell doesn't go to next line when at the end of the line

### ISSUE THREAD

**Issue by NicolasRannou** [banga/powerline-shell#245] opened 2016-08-10 08:30 UTC
I currently experience the following: If I type "hello" in my shell and there is not enough room to write the word, it doesn't print it on the next line but over-writes the current line.
<img width="592" alt="screen shot 2016-08-10 at 10 26 02 am" src="https://cloud.githubusercontent.com/assets/214063/17547002/1881a788-5ee5-11e6-918f-bd2a942fad37.png">

I if keep typing, it overwrites completly the current line then goes to the next line.
<img width="591" alt="screen shot 2016-08-10 at 10 29 29 am" src="https://cloud.githubusercontent.com/assets/214063/17547052/58384c60-5ee5-11e6-9b14-42665224b685.png">

mac OS Sierra (never tried powerline-shel before)

**Comment by b-ryan** [comment] 2017-06-20 19:16
@NicolasRannou I am currently unable to reproduce this. I am currently aggressively closing issues since there is a large backlog. If this is still an issue please re-open and let me know what shell you are using.

**Closed by b-ryan** 2017-06-20 19:16 UTC

**Comment by stefanomattia** [comment] 2018-01-24 15:25
I had the same problem. Turns out it was a problem related to LC_TYPE not being set.
Adding LC_CTYPE="en_US.UTF-8" to my  .bash_profile solved the issue.
