### ISSUE TITLE
What to do if the lines wrap incorrectly?

### ISSUE THREAD

**Issue by jkdf2** [banga/powerline-shell#146] opened 2014-06-16 17:07 UTC
![screen shot 2014-06-16 at 10 06 40 am](https://cloud.githubusercontent.com/assets/2641739/3290460/a8ecc2e0-f578-11e3-948c-5e2a21a83abb.png)
Running iTerm2 in Mac OSX, but this also occurs sometimes when I am running Linux Mint. Thanks!

**Comment by Woodstonelee** [comment] 2016-03-22 01:44
I have some similar problem with the line wraps. It goes back the beginning of the prompt.
![capture](https://cloud.githubusercontent.com/assets/5541602/13939751/13be0e18-efae-11e5-834d-14e68eb42c2d.PNG)

**Comment by insanityfarm** [comment] 2016-07-20 16:04
I'm having the exact same problem. For me it's happening in HyperTerm but not Terminal.app on macOS. I suspect it's a bug related to [this issue](http://askubuntu.com/questions/24358/how-do-i-get-long-command-lines-to-wrap-to-the-next-line), but I'm not sure why the same thing would behave differently in different terminals. It's possible that HyperTerm isn't properly setting the number of columns when the session is created, or something to that effect.

**Comment by insanityfarm** [comment] 2016-07-20 21:12
Dropping back in to note that there is currently an [issue open](https://github.com/zeit/hyperterm/issues/283) for HyperTerm that may be the cause of my particular problem. So it's not _necessarily_ powerline shell to blame, at least for me.

**Comment by b-ryan** [comment] 2017-06-20 18:36
Sorry this was never looked at properly. I tested bash on Ubuntu and everything was fine. I know that's very different from iTerm2 or HyperTerm. It's all I have to go on currently. Since this issue is really old and I'm trying to trim down the open issues, I'm going to close it. But please re-open if it hasn't been resolved. Make sure to get the latest powerline-shell before re-opening though.

**Closed by b-ryan** 2017-06-20 18:36 UTC
